### ISSUE TITLE
not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by verigle** [gpustack/gpustack#684]
**Describe the bug**

**Steps to reproduce**

deploy with docker compose 
```
docker pull gpustack/gpustack:main
```

deploy qwq-32b-preview
后端: llama-box

then chat with model of qwq-32b-preview

however there has an error
not enough values to unpack (expected 3, got 2)

**Expected behavior**
expected norm response

**Environment**

- GPUStack version: main( from docker hub with docker pull gpustack/gpustack:main)
- OS:  Ubuntu 22.04
- GPU: T4

**Additional context**

**Comment by verigle** [comment]
version: 
  server: 9eacc85
  UI: 1ac3768
GGUF model : QwQ-32B-Preview-Q4_K_M.gguf  (AI-ModelScope/QwQ-32B-Preview-GGUF)
CPU offloading: yes

**Comment by verigle** [comment]
log: Calculated resource claim for full offload model instance qwq-32b-preview-9gPHt, claim: memoryEstimate(fullOffloaded=True, ram=layerMemoryEstimate(uma=860664920, nonuma=1017951320, handleLayers=0), vrams=[layerMemoryEstimate(uma=15265722368, nonuma=16291233792, handleLayers=47), layerMemoryEstimate(uma=6289803264, nonuma=7315314688, handleLayers=17)], offloadLayers=65)

**Comment by verigle** [comment]
Can gpustack switch the GPU used based on the memory usage?

**Comment by verigle** [comment]
> <img alt="image" width="1488" src="https://private-user-images.githubusercontent.com/5697937/391518273-65962019-004e-4af0-bcf9-6ab9cfdc914e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDg5OTcsIm5iZiI6MTczMzIwODY5NywicGF0aCI6Ii81Njk3OTM3LzM5MTUxODI3My02NTk2MjAxOS0wMDRlLTRhZjAtYmNmOS02YWI5Y2ZkYzkxNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMDY1MTM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjAyMmY1ZWNhNjY0ZTAzNjE2MjQ0YWJlZGM1MmEwOTdiMzI0MWRkY2RjYjFkYjdmYzE2Zjc5NzY5ODIwMjViMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.e2MK6x5hxep2r979EpgIhyiIDgfNtq6noko1g7L5wa0"> I was able to do completions with QwQ. Can you provide the following info:
> 1. The server version shown in `Help -> Version`
> 2. which GGUF model are you using?
> 3. Is CPU offloading involving?

did you runing it with docker compose ?

**Comment by gitlawr** [comment]
> Can gpustack switch the GPU used based on the memory usage?

You can manually schedule to a specific GPU:
<img width="647" alt="image" src="https://github.com/user-attachments/assets/80998771-5c09-4fb8-9b6c-ec996e260703">


Let me take a closer look into the original issue.

**Comment by gitlawr** [comment]
There is a bug covering the root error which should be fixed in the latest main.

I tried deploying the `hf.co/bartowski/QwQ-32B-Preview-GGUF/QwQ-32B-Preview-Q4_K_M.gguf` model in a single-T4 node and here's the result(view the instance log in the UI to check):

45/65 layers are offloaded to GPU and it gets oom.
<img width="1203" alt="image" src="https://github.com/user-attachments/assets/e84f8b48-4c77-4e11-be4b-158fa65b53b0">

If setting `--gpu-layers=44` in advanced->backend parameter it can run.
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/988f3950-388e-482c-b983-b021ec563a13">

If you are interested in the details you can use [gguf-parser](https://github.com/gpustack/gguf-parser-go) by running `gguf-parser -hfr bartowski/QwQ-32B-Preview-GGUF -hff QwQ-32B-Preview-Q4_K_M.gguf --ctx-size 8192 --gpu-layers-step 1 --in-short --in-mib`. You can see the difference of the vram estimation as the followings:
<img width="697" alt="image" src="https://github.com/user-attachments/assets/4bf519d8-0244-40d1-b516-3d7d7f059407">

There can be estimation errors(~200 mib in this case) and you can tune the backend parameter and server parameter(check `--system-reserved` in [docs](https://docs.gpustack.ai/latest/cli-reference/start/)) to run better according to your setup.

We will continue the investigation on how to make it run easier out of the box.

**Comment by verigle** [comment]
> > Can gpustack switch the GPU used based on the memory usage?
> 
> You can manually schedule to a specific GPU: <img alt="image" width="647" src="https://private-user-images.githubusercontent.com/5697937/391942703-80998771-5c09-4fb8-9b6c-ec996e260703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNzQ5NzksIm5iZiI6MTczMzI3NDY3OSwicGF0aCI6Ii81Njk3OTM3LzM5MTk0MjcwMy04MDk5ODc3MS01YzA5LTRmYjgtOWI2Yy1lYzk5NmUyNjA3MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMDExMTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTlkYTI0MTk4NmQ2NzBmYjRjOGMxZjlkM2I3MmQ0Mzg3NGQzYTk5NjQ2ZDcxMzg5ZjYxNTE5ZWNlZmFlZjA1ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZdaD5FL2KCMwdSJdRrMF76R1xMV_dquDD63Kn_Wq_PI">
> 
> Let me take a closer look into the original issue.

can I select multi gpus manually?

**Comment by gitlawr** [comment]
It's not supported at the moment. Please feel free to file an enhancement issue.

**Comment by linyinli** [comment]
@verigle Although selecting multiple GPUs is not supported currently, you can use the `--tensor-split` parameter to allocate multiple GPUs for GGUF models, such as: `--tensor-split=1,1`

**Comment by Finenyaco** [comment]
Verified in main 7c08f5d and closed. If there are still any issues about this bug, please reopen this issue or file a new one.
