### ISSUE TITLE
Couldn't deploy ModelScope/iic/Whisper-large-v3 model on macOS

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#771]
**Describe the bug**

Couldn't deploy ModelScope/iic/Whisper-large-v3 model on macOS

**Steps to reproduce**

Run GPUStack on macOS and deploy iic/Whisper-large-v3 model from ModelScope.

**Result**

![image](https://github.com/user-attachments/assets/0c3f54bc-8752-4de0-b35c-7ce291ff3291)

**Environment**

- GPUStack version: v0.4.0
- OS: macOS 15.1
- GPU: M2 Ultra

**Comment by aiwantaozi** [comment]
Since ModelScope/iic/Whisper-large-v3 model need extra dependency when installing and faster-whisper's performance is better, so now supported  https://modelscope.cn/collections/Audio-3199751d3fa048 instead of the ModelScope/iic/Whisper-large-v3 model.

Synced models under https://huggingface.co/Systran to model scope https://modelscope.cn/collections/Audio-3199751d3fa048, so user can use whisper from model scope.
